FROM node:23-alpine AS build

ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

WORKDIR /app
COPY package.json package-lock.json* ./

RUN --mount=type=cache,target=/app/node_modules,id=npm \
    npm install --include=dev

COPY . .
RUN --mount=type=cache,target=/app/node_modules,id=npm \
    npm run build

FROM node:23-alpine AS production
WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install --omit=dev

COPY --from=build /app/dist ./dist

EXPOSE 3000
ENTRYPOINT ["npm", "run", "preview", "--", "--port=3000", "--host=0.0.0.0"]